### ISSUE TITLE
Most scripts not working since LSLib v1.19.4

### ISSUE THREAD

**Issue by VinTheMan** [LaughingLeader/BG3ModdingTools#4]
Assembly.LoadFrom seems to work
as well as clr.AddReference
but `from LSLib.LS import ...` & `from LSLib.LS.Enums import ...`
shows `**ModuleNotFoundError**`

`
Traceback (most recent call last):
  File "E:\BG3 Mods\Modding Tools\For Upload\scripts\convert_lsf.py", line 97, 
  in <module> run(lslib_dll, input_file, output_file, batch, in_type, out_type)
  File "E:\BG3 Mods\Modding Tools\For Upload\scripts\convert_lsf.py", line 29, in run
  from LSLib.LS import ResourceUtils, ResourceConversionParameters, ResourceLoadParameters # type: ignore ^^^^^^^^^^^^^^ModuleNotFoundError: No module named 'LSLib'`

**Comment by mycroftjr** [comment]
Note: for me, LSLib 1.19.5 initially gave the following error:
```
Traceback (most recent call last):
  File "D:\GitHub\BG3ModdingTools\scripts\extract_osiris.py", line 212, in <module>
    run(target_file, lslib_dll, output_dir)
  File "D:\GitHub\BG3ModdingTools\scripts\extract_osiris.py", line 61, in run
    Assembly.LoadFrom(str(lslib_dll.absolute()))
System.IO.FileLoadException: Could not load file or assembly 'file:///D:\ExportTool-v1.19.5\Tools\LSLib.dll' or one of its dependencies. Operation is 
not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///D:\ExportTool-v1.19.5\Tools\LSLib.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
```
However, after finding LSLib.dll, right-clicking it, and ticking the Unblock box near the bottom, the error returned to the one intially shown.

Interestingly, if you change the code to something like this:
```python
assembly = Assembly.LoadFrom(str(lslib_dll.absolute()))
print(assembly)
```
then you get `LSLib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null` for 1.19.5 (notice the bad version number) instead of something more like 1.18.7's `LSLib, Version=1.18.5.0, Culture=neutral, PublicKeyToken=null`.

**Comment by mycroftjr** [comment]
this code:
```python
try:
    types = ""
    for x in assemb.GetTypes():
        types = types + str(x) + ", "
    print(types)
except Exception as e:
    print(e)
    for y in e.LoaderExceptions:
        print(y)         
```
Lets us examine the types in the assembly, or the errors if they could not be loaded. It works fine for 1.18.7, but for 1.19.5, it prints a lot of errors:
```
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
Could not load type 'System.IO.Stream' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. x2
Virtual Static Method. x16
Could not load type 'System.IO.BinaryReader' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load type 'System.IO.BinaryWriter' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Could not load type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Method 'Go' in type 'Runner' from assembly 'LSLib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```
give the 4.0.0.0 in the errors, it might have something to do with LSLib now requiring .NET 8?

**Comment by mycroftjr** [comment]
Ok, at least for me, this fixes it:
```
import pythonnet
pythonnet.load('coreclr')
```
before the `import clr`

**Comment by VinTheMan** [comment]
> Ok, at least for me, this fixes it:
> 
> ```
> import pythonnet
> pythonnet.load('coreclr')
> ```
> 
> before the `import clr`

@mycroftjr 
Wow this works!!
How did u figure it out !? I am super curious
I was thinking that it might be missing reference when loading DLLs and even rebuilt the LSLib with altered namespace myself but didn't solve the problem.

Is it bc of .NET 8 that we now need to use coreclr ?

**Comment by mycroftjr** [comment]
> > Ok, at least for me, this fixes it:
> > ```
> > import pythonnet
> > pythonnet.load('coreclr')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > before the `import clr`
> 
> @mycroftjr Wow this works!! How did u figure it out !? I am super curious I was thinking that it might be missing reference when loading DLLs and even rebuilt the LSLib with altered namespace myself but didn't solve the problem.
> 
> Is it bc of .NET 8 that we now need to use coreclr ?

I no longer remember how I figured it out, but I think googling and https://github.com/LaughingLeader/BG3ModdingTools/issues/3#issuecomment-1953405606 put me onto pythonnet and then I experimented with stuff until it worked lol
